In [1]:
import numpy as np
num=np.array([1,2,3,4,5])
print(num[1:4])
print(num[2:])
print(num[-3:-1])

[2 3 4]
[3 4 5]
[3 4]


In [2]:
import numpy as np
num=np.array([1,2,3,4,5],dtype='S')
print(num.dtype) #Datatype detecting

|S1


In [4]:
# Using numpy for diff datatypes
import numpy as np
num=np.array([1,2,3,4,5])
n=num.astype(bool)
new=num.astype(float)
newn=num.astype('S')
print(num.shape)
print(newn)
print(new)
print(n)

(5,)
[b'1' b'2' b'3' b'4' b'5']
[1. 2. 3. 4. 5.]
[ True  True  True  True  True]
