                           One-Hot Encoding
1. What is One-Hot Encoding?

A technique used to convert categorical data into numerical form.

Each category is represented as a binary vector (0s and 1s).

2. Why Do We Use It?

Machine learning models cannot work directly with text labels.

One-hot encoding allows models to understand categories without implying any order.

3. How It Works

Suppose you have 3 categories:
["Red", "Green", "Blue"]

One-hot encoding converts them into:
| Category | One-Hot Vector |
| -------- | -------------- |
| Red      | [1, 0, 0]      |
| Green    | [0, 1, 0]      |
| Blue     | [0, 0, 1]      |

Each category gets:

A unique position in the vector

A 1 in its position

0s everywhere else

4. Features of One-Hot Encoding

No ordinal relationship between categories

Easy for models to interpret

Used widely in ML and DL (classification problems)

5. Where It Is Used

Converting text labels into numeric form

NLP (words → vectors)

Neural networks (target labels like "cat", "dog")

Multiple classification tasks

6. Advantages

Simple and effective

No ordering is assumed between categories

Makes categorical data suitable for ML algorithms

7. Disadvantages

Increases dimensionality (high number of categories → very big vectors)

Not suitable for large vocabulary tasks (e.g., NLP with thousands of words)


In [52]:
import numpy as np

# Suppose we have 5 classes and a label y = 2
num_classes = 5
y = 2

# One hot encoding
one_hot = np.eye(num_classes)[y]
print("One Hot Encoding of label 2:", one_hot)


One Hot Encoding of label 2: [0. 0. 1. 0. 0.]


In [53]:
import tensorflow as tf

labels = [0, 2, 3]   # class indices
num_classes = 5

# Convert to one-hot
one_hot = tf.keras.utils.to_categorical(labels, num_classes)
print(one_hot)




[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [54]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Dummy dataset
X = np.random.rand(10, 4)   # 10 samples, 4 features each
y = [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

# One-hot encode labels
y_encoded = tf.keras.utils.to_categorical(y, num_classes=5)

# Simple model
model = Sequential([
    Dense(8, activation='relu', input_shape=(4,)),
    Dense(5, activation='softmax')   # 5 classes → one-hot output
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X, y_encoded, epochs=10, verbose=1)


Epoch 1/10


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 815ms/step - accuracy: 0.3000 - loss: 1.5671
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.3000 - loss: 1.5663
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.3000 - loss: 1.5654
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.3000 - loss: 1.5645
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.3000 - loss: 1.5637
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.3000 - loss: 1.5628
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.3000 - loss: 1.5619
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.3000 - loss: 1.5611
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.3000 - loss: 1.5602
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.3000 - loss: 1.5593


In [55]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# ---------------------------
# 1. Prepare dataset
# ---------------------------
# Features: 10 samples, 4 features each
X = np.random.rand(10, 4)

# Labels: class indices (0 to 4)
y = [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

# One-hot encoding
num_classes = 5
y_onehot = tf.keras.utils.to_categorical(y, num_classes)

# ---------------------------
# 2. Build model
# ---------------------------
model = Sequential([
    Dense(8, activation='relu', input_shape=(4,)),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# ---------------------------
# 3. Train model
# ---------------------------
model.fit(X, y_onehot, epochs=10, verbose=1)

# ---------------------------
# 4. Test prediction
# ---------------------------
test_sample = np.random.rand(1, 4)
prediction = model.predict(test_sample)
print("Test sample:", test_sample)
print("Predicted class (one-hot):", prediction)
print("Predicted class index:", np.argmax(prediction))


Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.1000 - loss: 1.6285
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.1000 - loss: 1.6279
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.1000 - loss: 1.6273
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.1000 - loss: 1.6267
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.1000 - loss: 1.6260
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.1000 - loss: 1.6254
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.1000 - loss: 1.6248
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.1000 - loss: 1.6241
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.1000 - loss: 1.6235
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.1000 - loss: 1.6229
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
Test sample: [[0.39312168 0.0674383  0.95066299 0.54522166]]
Predicted class (one-hot): [[0.17188168 0.1545139  0.19605969 0.24414968